{"name": "test_login_scenarios[wrong_user-secret_sauce-error]", "status": "broken", "statusDetails": {"message": "KeyError: 'label_type'", "trace": "self = <allure_pytest.listener.AllureListener object at 0x0000027FD97AFB60>, item = <Function test_login_scenarios[wrong_user-secret_sauce-error]>\n\n    @pytest.hookimpl(hookwrapper=True)\n    def pytest_runtest_teardown(self, item):\n        yield\n        uuid = self._cache.get(item.nodeid)\n        test_result = self.allure_logger.get_test(uuid)\n        test_result.historyId = get_history_id(\n            test_result.fullName,\n            test_result.parameters,\n            original_values=self.__get_pytest_params(item)\n        )\n>       test_result.labels.extend([Label(name=name, value=value) for name, value in allure_labels(item)])\n\nvenv\\Lib\\site-packages\\allure_pytest\\listener.py:145: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nitem = <Function test_login_scenarios[wrong_user-secret_sauce-error]>\n\n    def allure_labels(item):\n        unique_labels = dict()\n        labels = set()\n        for mark in item.iter_markers(name=ALLURE_LABEL_MARK):\n>           label_type = mark.kwargs[\"label_type\"]\nE           KeyError: 'label_type'\n\nvenv\\Lib\\site-packages\\allure_pytest\\utils.py:61: KeyError"}, "description": "Test different login scenarios", "parameters": [{"name": "username", "value": "'wrong_user'"}, {"name": "password", "value": "'secret_sauce'"}, {"name": "expected_result", "value": "'error'"}], "start": 1744386225626, "stop": 1744386232798, "uuid": "5c2d4552-c7ff-47bc-a317-c318a7d9b2d9", "historyId": "a23987a8e31de0b294db4ba2140c8502", "testCaseId": "3b6c0d1ca0268f3d666f1f08bb6a9593", "fullName": "tests.test_login_page#test_login_scenarios"}